dataset_name: default
dataset_path: TheFinAI/greek-fns-2023
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "."
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
num_fewshot: 0
task: GRFNS2023
test_split: test
training_split: train
